### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by turner485** [vadimkacool/Elden-Ring-Death-Counter-OBS#2]
tried to get this working my self i got this error;
```
[DeathCounter.py] Traceback (most recent call last):
[DeathCounter.py]   File "C:\Users/Ben/Documents/OBS_ASSETS/Elden-Ring-Death-Counter-OBS-main/Elden-Ring-Death-Counter-OBS-main\DeathCounter.py", line 47, in attach
[DeathCounter.py]     address = getPointerAddress(pm.base_address + pointer, offsets=[offset])
[DeathCounter.py]                                 ^^^^^^^^^^^^^^^
[DeathCounter.py]   File "C:\Users\Ben\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymem\__init__.py", line 454, in base_address
[DeathCounter.py]     return self.process_base.lpBaseOfDll
[DeathCounter.py]            ^^^^^^^^^^^^^^^^^
[DeathCounter.py]   File "C:\Users\Ben\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymem\__init__.py", line 435, in process_base
[DeathCounter.py]     raise pymem.exception.ProcessError("Could not find process first module")
[DeathCounter.py] pymem.exception.ProcessError: Could not find process first module`
```

I have followed the steps correctly.

**Comment by Kam1k4dze** [comment]
Script is outdated. Use this instead https://www.nexusmods.com/eldenring/mods/2989

**Comment by turner485** [comment]
Great! thanks so much dude!
